baseURL                 = "https://jde.github.io/"
locale                  = "es-es"
title                   = "JDE Integra Solutions"
defaultContentLanguage  = "es"
hasCJKLanguage          = false
theme                   = "hugo-theme-stack"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
